#pragma kernel CSComputeMaxSimilarity
#pragma enable_d3d11_debug_symbols

#define MAX_ATOM_COUNT 60 
#define SMILES_MAX_LENGTH 256
#define FP_SIZE 512

int genCount; 
int refCount; 

float minSimilarity; 



StructuredBuffer<bool> generatedFP;

StructuredBuffer<bool> referenceFP;

RWStructuredBuffer<float> maxSimilarityOutput;
float CalculateTanimoto(bool fpA[FP_SIZE], bool fpB[FP_SIZE], int size)
{
    int intersection = 0;
    int _union = 0;
    for (int i = 0; i < size; i++)
    {
        if (fpA[i] || fpB[i])
            _union++;
        if (fpA[i] && fpB[i]) intersection++;
    }
    return _union == 0 ? 0.0f : (float) intersection / _union;
}

[numthreads(32, 1, 1)]
void CSComputeMaxSimilarity(uint3 dispatchThreadID : SV_DispatchThreadID)
{
    int genIdx = dispatchThreadID.x;
    if (genIdx >= genCount) return;

    
    bool genFP [FP_SIZE];
    for (int i = 0; i < FP_SIZE; i++)
    {
        genFP[i] = generatedFP[genIdx * FP_SIZE + i];
    }

    
    float maxSim = 0.0f;
    for (int refIdx = 0; refIdx < refCount; refIdx++)
    {
        
        bool refFP [FP_SIZE];
        for (int i = 0; i < FP_SIZE; i++)
        {
            refFP[i] = referenceFP[refIdx * FP_SIZE + i];
        }

        
        float sim = CalculateTanimoto(genFP, refFP, FP_SIZE);
        if (sim > maxSim) maxSim = sim;

        
        if (maxSim >= 1.0f) break;
    }

    
    maxSimilarityOutput[genIdx] = maxSim >= minSimilarity ? maxSim : 0.0f;
}